# Generated by Django 6.1 on 2026-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_ticket_bureau_ticket_it_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='intervention_duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
