# Generated by Django 6.1 on 2026-09-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ticket_intervention_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='user',
            name='login_name',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ticket_created', 'Ticket créé'), ('assignment', 'Assignation'), ('status', 'Statut'), ('comment', 'Commentaire'), ('resolution', 'Résolution'), ('request', 'Demande RH')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=60, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Employé'), ('technician', 'IT Technician'), ('hr', 'RH'), ('superadmin', 'SuperAdmin')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('leave', 'Demande de congé'), ('advance', "Demande d'avance"), ('general', 'Demande')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('destination', models.CharField(choices=[('direction', 'Direction'), ('hr', 'RH'), ('administration', 'Administration')], default='hr', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('motif', models.TextField(blank=True)),
                ('leave_type', models.CharField(blank=True, choices=[('annual', 'Congé annuel'), ('sick', 'Congé maladie'), ('unpaid', 'Congé sans solde'), ('other', 'Autre')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='TND', max_length=8)),
                ('admin_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employeerequest'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('weekend', 'Week-end'), ('holiday', 'Jour férié'), ('leave', 'Congé')], default='present', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
